name: sibaba
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  datetime_picker_formfield: ^2.0.0
  dio: ^4.0.4
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_html: ^2.2.1
  freezed: ^1.0.2
  geocoding: ^2.0.4
  get: ^4.3.8
  get_it: ^7.2.0
  google_fonts: ^2.1.0
  google_maps_flutter: ^2.1.3
  html_editor_enhanced: ^2.4.0+1
  image_cropper: ^1.5.1
  image_picker: ^0.8.4+11
  injectable: ^1.5.0
  json_annotation: ^4.4.0
  location: ^4.3.0
  logger: ^1.1.0
  logging: ^1.0.2
  multi_select_flutter: ^4.1.2
  open_file: ^3.2.1
  path_provider: ^2.0.9
  pretty_dio_logger: ^1.1.1
  shared_preferences: ^2.0.13
  shimmer: ^2.0.0
  stepper: ^0.0.2
  syncfusion_flutter_pdf: ^20.1.52-beta
  syncfusion_flutter_xlsio: ^20.1.52-beta
  url_launcher: ^6.0.20
  velocity_x: ^3.3.0

dev_dependencies:
  build_runner: ^2.1.5
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.2
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
